### ISSUE TITLE
broken link to  "full example"

### ISSUE THREAD

**Issue by rasmuspjohansson** [akshaykvnit/pl-sem-seg#1]
Im searching for a good example of how to train unets with different  backbones (resnet50 etc )with pytorch lightning and your page is what comes up. Awesome work!
The link to the new (maintained?) version is however broken so I dont know if I should use this(pl-sem-seg) project or something else.
Kind regards Rasmus

**Comment by akshaykulkarni07** [comment]
Hey, sorry about the late reply. The official PyTorch Lightning example is [here](https://github.com/Lightning-AI/lightning/blob/master/examples/pl_domain_templates/semantic_segmentation.py). I had contributed the original example but it has since been significantly modified (and moved, which caused the broken link). I would suggest using the new official example because I'm not sure whether my usage of PyTorch Lightning is correct anymore (since PL has changed many of their code practices and I did not really keep up with them).
